version: '3.8'
services:
  ml-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - MODEL_PATH=/save/modelMnist1.keras
    networks:
      - ml-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ml-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - ml-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    volumes:
      - ./app/mlruns:/mlruns 
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    networks:
      - ml-network

networks:
  ml-network:
