name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  MLFLOW_TRACKING_URI: "file:${{ github.workspace }}/mlruns"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.16

    - name: Create mlruns directory
      run: |
        mkdir -p ./mlruns
        chmod -R 777 ./mlruns
        ls -ld ./mlruns

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Debug environment variables
      run: |
        echo "MLFLOW_TRACKING_URI=${{ env.MLFLOW_TRACKING_URI }}"

    - name: Run tests
      run: |
        export TF_CPP_MIN_LOG_LEVEL=2
        pytest app/test/

    - name: Build Docker image
      run: |
        docker build -t ml-api .
